<!--
document.writeln("<header>");
document.writeln("  <h1 class=\"logo\">");
document.writeln("    <dt><a href=\"index.asp\">【中文版】</a> <a href=\"#\">【English】</a></dt>");
document.writeln("    <dd><img src=\"css/images/fuwu.png\"></dd>");
document.writeln("  </h1>");
document.writeln("</header>");
document.writeln("<div id=\"nav\"> ");
document.writeln("  <!-- [navigation] -->");
document.writeln("  <div style=\"width:960px; margin:0 auto\">");
document.writeln("    <ul class=\"sf-menu\" id=\"navigation\">");
document.writeln("      <li><a href=\"index.asp\" style=\"border:none\">返回首页</a></li>");
document.writeln("      <li><a href=\"yingxiao.html\">香氛营销</a>");
document.writeln("      <ul class=\"sub-menu\">");
document.writeln("          <li class=\"menu-item\"><a href=\"yingxiao.html\">香氛营销</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"zhuanjia.html\">香氛专家</a></li>");
document.writeln("  		  <li class=\"menu-item\"><a href=\"yanjiu.html\">香氛研究</a></li>");
document.writeln("        </ul>");
document.writeln("      </li>");
document.writeln("      <li class=\"menu-item\"><a href=\"fangan.html\">解决方案</a>");
document.writeln("        <ul class=\"sub-menu\">");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView1.html\">酒店会所</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView2.html\">娱乐场所</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView3.html\">潮流购物</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView4.html\">时尚造型</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView5.html\">高端餐饮</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView6.html\">医疗机构</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView7.html\">工作空间</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"fanganView8.html\">健身会所</a></li>");
document.writeln("<li class=\"menu-item\"><a href=\"fanganView9.html\">婚礼庆典</a></li>");
document.writeln("        </ul>");
document.writeln("      </li>");
document.writeln("      <li><a href=\"jingyou.html\">香氛精油</a>");
document.writeln("      <ul class=\"sub-menu\">");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView1.html\">美丽心情系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView2.html\">激活畅爽系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView3.html\">美味诱惑系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView4.html\">花香怡人系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView5.html\">甜蜜缤纷系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView6.html\">自然清新系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView7.html\">古老神秘系列</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"jingyouView8.html\">高贵奢华系列</a></li>");
document.writeln("<li class=\"menu-item\"><a href=\"jingyouView9.html\">稳重低调系列</a></li>");
document.writeln("        </ul></li>");
document.writeln("      <li><a href=\"shebei.html\">扩香设备</a></li>");
document.writeln("      <li><a href=\"anli.html\">成功案例</a></li>");
document.writeln("      <li><a href=\"aboutUs.html\">关于我们</a></li>");
document.writeln("      <li><a href=\"news.asp\">新闻中心</a></li>");
document.writeln("      <li class=\"current\"><a href=\"contact.html\">联系我们</a>");
document.writeln("        <ul  class=\"sub-menu\">");
document.writeln("          <li class=\"menu-item\"><a href=\"contact.html\">联系我们</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"callcenter.html\">客服中心</a></li>");
document.writeln("          <li class=\"menu-item\"><a href=\"service.html\">售后服务</a></li>");
document.writeln("        </ul>");
document.writeln("      </li>");
document.writeln("    </ul>");
document.writeln("  </div>");
document.writeln("  <!-- .navigation --> ");
document.writeln("</div>");
//-->